services:
  hermes.database:
    container_name: hermes.database
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./containers/hermes-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    container_name: hermes.server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=hermes.database;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - PORT=${PORT}
      - EMAIL_SENDER_USERNAME=${EMAIL_SENDER_USERNAME}
      - EMAIL_SENDER_PASSWORD=${EMAIL_SENDER_PASSWORD}
      - REACT_CLIENT_URL=${REACT_CLIENT_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ALARM_EMAIL=${ALARM_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MONITORED_SERVER_URL=${MONITORED_SERVER_URL}
      - DOCKER_BAN_LIST_PATH=${DOCKER_BAN_LIST_PATH}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${BAN_LIST_PATH}:${DOCKER_BAN_LIST_PATH}
    depends_on:
      hermes.database:
        condition: service_healthy

  elasticsearch:
    container_name: elastic
    image: elasticsearch:8.15.1
    ports:
      - "9200:9200"
    volumes:
      - ./containers/elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  logstash:
    image: logstash:8.15.1
    container_name: logstash
    restart: always
    volumes:
      - ${LOG_PATH}:/logs.txt
      - ./containers/logstash/pipeline/:/usr/share/logstash/pipeline/
    command: logstash -r -f /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m" 
      xpack.monitoring.enabled: "false"  

volumes: 
  elasticsearch-data: