services:
  hermes.database:
    image: postgres:latest
    container_name: hermes.database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./containers/hermes-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    container_name: hermes.server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=${CONNECTION_STRING}
      - SMTP_SERVER=${SMTP_SERVER}
      - PORT=${PORT}
      - EMAIL_SENDER_USERNAME=${EMAIL_SENDER_USERNAME}
      - EMAIL_SENDER_PASSWORD=${EMAIL_SENDER_PASSWORD}
      - REACT_CLIENT_URL=${REACT_CLIENT_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      hermes.database:
        condition: service_healthy